r"""
This file was *autogenerated* from 03112018.tex with sagetex.sty
version 2015/08/26 v3.0-92d9f7a. It contains the contents of all the
sageexample environments from 03112018.tex. You should be able to
doctest this file with "sage -t 03112018_doctest.sage".

It is always safe to delete this file; it is not used in typesetting your
document.

Sage commandline, line 3::

sage: factor(x^2 + 2*x + 1)(x + 999)^2

"""
