## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file 03112018.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5)## This file (03112018.sagetex.sage) was *autogenerated* from 03112018.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('03112018', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = _sage_const_3 
 _st_.commandline(_sage_const_0 , r"""
sage: factor(x^2 + 2*x + 1)(x + 999)^2
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_5 )
_st_.endofdoc()

