## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file nuevo_1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_33 = Integer(33); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7)## This file (nuevo_1.sagetex.sage) was *autogenerated* from nuevo_1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('nuevo_1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
try:
 _st_.current_tex_line = _sage_const_33 
 _st_.inline(_sage_const_0 , latex(_sage_const_7 //_sage_const_2 ))
except:
 _st_.goboom(_sage_const_33 )
_st_.endofdoc()

